### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by sergeyklay**
@duythien Create please a composer repo from current composer.json for phalcon-tip (currently in PR)

### CODE REVIEW

**Comment by duythien** [comment]
Done

**Comment by sergeyklay** [comment]
@duythien It seens no

https://packagist.org/search/?q=zphalcon - 404
https://packagist.org/packages/zphalcon/phalcon-tip - 404

**Comment by stackphysics** [comment]
Checking again:)

**Comment by sergeyklay** [comment]
:+1:

**Pull request merged**
